<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-DHGB96Q" failures="3" tests="18" name="sanity.ShopDemo" time="117.597" errors="0" timestamp="2024-12-28T11:50:19 IST" skipped="9">
  <testcase classname="sanity.ShopDemo" name="test01_verifySearchForSpecificProduct" time="5.412"/>
  <system-out/>
  <testcase classname="sanity.ShopDemo" name="test03_verifyAboutAtidText" time="4.304"/>
  <system-out/>
  <testcase classname="sanity.ShopDemo" name="test05_verifyHighestProductPrice" time="6.645">
    <skipped/>
  </testcase> <!-- test05_verifyHighestProductPrice -->
  <system-out/>
  <testcase classname="sanity.ShopDemo" name="test05_verifyHighestProductPrice" time="7.102">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at extensions.Verifications.verifyTextContainedInElement(Verifications.java:110)
at sanity.ShopDemo.test05_verifyHighestProductPrice(ShopDemo.java:59)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
    </failure>
  </testcase> <!-- test05_verifyHighestProductPrice -->
  <system-out/>
  <testcase classname="sanity.ShopDemo" name="test02_SearchForKeywordAndVerifyProductsCount" time="5.704"/>
  <system-out/>
  <testcase classname="sanity.ShopDemo" name="test07_verifySearchProductsElementLocation" time="6.778">
    <failure message="The following asserts failed:
	expected [198] but found [217],
	expected [43] but found [42],
	expected [198] but found [217],
	expected [43] but found [42],
	expected [198] but found [217],
	expected [43] but found [42],
	expected [198] but found [217],
	expected [43] but found [42]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [198] but found [217],
expected [43] but found [42],
expected [198] but found [217],
expected [43] but found [42],
expected [198] but found [217],
expected [43] but found [42],
expected [198] but found [217],
expected [43] but found [42]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at extensions.Verifications.verifyElementOrientaion(Verifications.java:269)
at sanity.ShopDemo.test07_verifySearchProductsElementLocation(ShopDemo.java:116)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
    </failure>
  </testcase> <!-- test07_verifySearchProductsElementLocation -->
  <system-out/>
  <testcase classname="sanity.ShopDemo" name="test04_verifyProductImage" time="8.357">
    <skipped/>
  </testcase> <!-- test04_verifyProductImage -->
  <system-out/>
  <testcase classname="sanity.ShopDemo" name="test05_verifyHighestProductPrice" time="6.007">
    <skipped/>
  </testcase> <!-- test05_verifyHighestProductPrice -->
  <system-out/>
  <testcase classname="sanity.ShopDemo" name="test05_verifyHighestProductPrice" time="8.797">
    <skipped/>
  </testcase> <!-- test05_verifyHighestProductPrice -->
  <system-out/>
  <testcase classname="sanity.ShopDemo" name="test06_verifyDetailsOfProductAddedToCart" time="20.754"/>
  <system-out/>
  <testcase classname="sanity.ShopDemo" name="test07_verifySearchProductsElementLocation" time="4.878">
    <skipped/>
  </testcase> <!-- test07_verifySearchProductsElementLocation -->
  <system-out/>
  <testcase classname="sanity.ShopDemo" name="test02_SearchForKeywordAndVerifyProductsCount" time="4.999"/>
  <system-out/>
  <testcase classname="sanity.ShopDemo" name="test04_verifyProductImage" time="4.944">
    <skipped/>
  </testcase> <!-- test04_verifyProductImage -->
  <system-out/>
  <testcase classname="sanity.ShopDemo" name="test04_verifyProductImage" time="4.815">
    <failure message="Error Comparing Image File: FindFailed: C:\\Automation\\Projects\\Selenium4Java\\Images\\anchorBraceletImage.png: (156x156) in R[0,0 1280x1024]@S(0)
  Line 2287, in file Region.java
" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error Comparing Image File: FindFailed: C:\\Automation\\Projects\\Selenium4Java\\Images\\anchorBraceletImage.png: (156x156) in R[0,0 1280x1024]@S(0)
  Line 2287, in file Region.java

at org.testng.Assert.fail(Assert.java:99)
at extensions.Verifications.visualElement(Verifications.java:185)
at sanity.ShopDemo.test04_verifyProductImage(ShopDemo.java:50)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
    </failure>
  </testcase> <!-- test04_verifyProductImage -->
  <system-out/>
  <testcase classname="sanity.ShopDemo" name="test04_verifyProductImage" time="3.809">
    <skipped/>
  </testcase> <!-- test04_verifyProductImage -->
  <system-out/>
  <testcase classname="sanity.ShopDemo" name="test07_verifySearchProductsElementLocation" time="4.489">
    <skipped/>
  </testcase> <!-- test07_verifySearchProductsElementLocation -->
  <system-out/>
  <testcase classname="sanity.ShopDemo" name="test01_verifySearchForSpecificProduct" time="3.451"/>
  <system-out/>
  <testcase classname="sanity.ShopDemo" name="test07_verifySearchProductsElementLocation" time="6.352">
    <skipped/>
  </testcase> <!-- test07_verifySearchProductsElementLocation -->
  <system-out/>
</testsuite> <!-- sanity.ShopDemo -->
